version: '2'

services:
  github-releases-notifier:
    restart: always
    image: justwatch/github-releases-notifier
    environment:
      - GITHUB_TOKEN=XXX
      - SLACK_HOOK=https://hooks.slack.com/services/T02MASDF7/B6WERHYRZ/XXX
    command:
      - '-r=golang/go'
      - '-r=justwatchcom/elasticsearch_exporter'
      - '-r=justwatchcom/gopass'
      - '-r=justwatchcom/sql_exporter'
      - '-r=kubernetes/minikube'
      - '-r=prometheus/prometheus'
      - '-r=shurcooL/githubql'
